#logging:
#  level:
#    root: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gk_user?useSSL=true&serverTimezone=UTC
    username: temp
    password: 123
mybatis:
  mapper-locations:
    - classpath:mapper/**xml