server:
  port: 60101
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/gk_user?useSSL=true&serverTimezone=UTC
    username: temp
    password: 123
  messages:
    basename:

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:org/aurifolia/ginkgo/user/mapper/xml/*.xml