server:
  port: 60000
spring:
  application:
    name: outer-gateway-service
  messages:
    basename: result-message
  cloud:
    gateway:
      default-filters:
        - Authentication
      routes:
        - id: user-service
          uri: http://localhost:60100
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1